language: php

php:
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - travis_retry composer install --no-interaction --prefer-source

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'